# nixpacks.toml

providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"

[build]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/refs/tags/23.05.tar.gz"

[phases.setup]
nixPkgs = [
  "python312",
  "gcc",
  "mesa",
  "pkg-config",
  "glib",
  "libGL",
  "libGLU",
  "libSM",
  "libXext",
  "libXrender"
]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools<81",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Linking OpenCV shared libraries…'",
  '''for lib in libGL.so.1 libglib-2.0.so.0 libgthread-2.0.so.0 libSM.so.6 libXext.so.6 libXrender.so.1; do
    path=$(find /nix/store -type f -name "$lib" | head -n1) &&
    ln -sf "$path" "/usr/lib/$lib" &&
    echo "→ linked $lib" ||
    echo "⚠️ $lib not found";
  done''',
  "echo 'Verifying cv2 linkage:'",
  "ldd /opt/venv/lib/python3.12/site-packages/cv2/*.so"
]

[start]
cmd = "gunicorn run:app --bind 0.0.0.0:$PORT"
