# nixpacks.toml

providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"

[build]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/refs/tags/23.05.tar.gz"

[phases.setup]
nixPkgs = [
  "python312",
  "gcc",
  "mesa",
  "pkg-config",
  "glib",
  "libGL",
  "libGLU",
  "libSM",
  "libXext",
  "libXrender"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools<81",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Skipping manual symlinks, trusting Nix environment'",
  "ldd /opt/venv/lib/python3.12/site-packages/cv2/*.so || echo 'ldd check failed (non-blocking)'"
]

[start]
cmd = "gunicorn run:app --bind 0.0.0.0:$PORT"
